[package]
name = "histeq"
version = "0.1.0"
edition = "2021"


[dependencies]
ndarray = "*"
ndarray-stats = "*"
png = "*"
itertools = "*"
image = "0.24"
num-traits = {version = "*", features = ["std"]}
byteorder = "*"
plotters = "*"

[features]
blas = ["ndarray/blas"]