[package]
name = "histeq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "*"
ndarray-stats = "*"
lodepng = "*"
itertools = "*"
image = "*"
num-traits = "*"